name: id_generator
description: A comprehensive Dart library for generating secure, customizable random IDs with support for numeric, alphabetic, special characters, and mixed combinations.
version: 1.0.0
repository: https://github.com/mohamedmaher-dev/id_generator

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
